### ISSUE TITLE
use for teaching?

### ISSUE THREAD

**Issue by mebrooks** [ices-eg/tc_tcsai2018#2]
Hi,

I just randomly found this code and think it could be useful. It does a lot of things that we're hoping to teach in an intro course at DTU. Is it ok if I use this code? Is there anything I need to be aware of?

Cheers,
Mollie

**Comment by colinpmillar** [comment]
Hi,
These materials are free to use, feel free to mention that you got them from the ICES Training course :)
Cheers,
Colin

**Comment by mebrooks** [comment]
Thanks Colin!
